### ISSUE TITLE
line-height css property

### ISSUE THREAD

**Issue by jormungandhr** [hteumeuleu/caniemail#138] opened 2021-03-05 11:23 UTC
How does support for css `line-height` look? Can it be added to the website?

**Comment by MichaelvanLaar** [comment] 2021-04-12 13:57
As always, Campaign Monitor has some input: https://www.campaignmonitor.com/css/text-fonts/line-height/

**Comment by morozover** [comment] 2021-09-13 08:10
> As always, Campaign Monitor has some input: https://www.campaignmonitor.com/css/text-fonts/line-height/

The problem is the Campaign Monitor is does not updated since 2017:

![image](https://user-images.githubusercontent.com/17902666/133047492-ffed9ede-aa6d-4824-baf4-37dc1f90e8d6.png)

**Comment by morozover** [comment] 2021-09-13 08:11
Could you please add support for `line-height` style?

**Comment by rootwork** [comment] 2021-10-01 21:45
https://caniuse.email (a different project) reports line-height support among all tested email clients.

**Comment by hteumeuleu** [comment] 2021-10-02 08:42
I've done my own test and I'm suprised by the results on caniuse.email. I'm more in line with Campaign Monitor here and confirm the behavior is buggy on the Outlooks on Windows. 

https://www.caniemail.com/features/css-line-height/

**Comment by rootwork** [comment] 2021-10-04 21:00
Thanks! This is what I suspected. I appreciate the updated tests and listing!

**Comment by hteumeuleu** [comment] 2021-10-05 06:55
I'm closing this for now, but will update the page with notes if I can figure out Outlook's behavior on fixed units.

**Closed by hteumeuleu** 2021-10-05 06:55 UTC
Labels: Data request
